name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/sttup-go@v2 
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go


